from app.schemas.task_catalog import (
    TrialTaskDefinition,
    TrialTaskEvent,
    TrialTaskRubricCriterion,
    TrialTaskStep,
)
from app.tasks.evaluation_rules import TASK_EVALUATION_RULES


TASK_ESTIMATED_MINUTES = {
    "F-01": "15–18 分钟",
    "F-02": "12–15 分钟",
    "F-03": "15–20 分钟",
    "A-01": "15–18 分钟",
    "A-02": "15–20 分钟",
    "A-03": "15–18 分钟",
    "P-01": "15–20 分钟",
    "P-02": "12–15 分钟",
    "P-03": "15–20 分钟",
    "M-01": "12–15 分钟",
    "M-02": "15–18 分钟",
    "M-03": "15–20 分钟",
}


def _step(
    step_id: str,
    title: str,
    input_mode: str,
    instruction: str,
    constraint: str,
) -> TrialTaskStep:
    return TrialTaskStep(
        id=step_id,
        title=title,
        input_mode=input_mode,
        instruction=instruction,
        constraint=constraint,
    )


def _rubric(primary_skill: str, task_behavior: str) -> list[TrialTaskRubricCriterion]:
    return [
        TrialTaskRubricCriterion(
            dimension=primary_skill,
            weight=40,
            observable_behavior=task_behavior,
        ),
        TrialTaskRubricCriterion(
            dimension="证据与推理",
            weight=25,
            observable_behavior="引用任务材料支持判断，并区分事实、假设和待验证项。",
        ),
        TrialTaskRubricCriterion(
            dimension="方案完整性",
            weight=20,
            observable_behavior="给出边界、成功信号、风险或失败后的处理方式。",
        ),
        TrialTaskRubricCriterion(
            dimension="动态调整",
            weight=15,
            observable_behavior="在中途事件出现后重新判断，并说明保持或调整的依据。",
        ),
    ]


TASK_CATALOG: dict[str, TrialTaskDefinition] = {
    "F-01": TrialTaskDefinition(
        id="F-01",
        track="feature",
        title="AI 到底应该进入创作链路的哪一步？",
        subtitle="判断 AI 介入点，而不是先堆功能",
        role_type="AI 功能产品经理",
        work_stage="机会判断",
        primary_skill="用户洞察",
        supporting_skills=["方案与交互", "数据驱动"],
        estimated_minutes="25–35 分钟",
        difficulty="基础",
        role="你是一款内容创作产品的 AI 产品经理。",
        background="团队准备把 AI 加入创作链路，但用户反馈同时涉及灵感不足、操作复杂、结果不可控等问题。",
        goal="选择一个最值得由 AI 介入的问题，给出最小验证方案。",
        constraints=["只能选择一个核心问题", "首轮验证只允许一次模型调用", "必须保留用户控制权"],
        steps=[
            _step("problem", "判断问题类型", "单选 + 说明", "选择单一任务或定制任务，并重新定义用户阻塞点。", "只保留一个核心问题。"),
            _step("evidence", "引用证据", "多选 + 说明", "至少引用两项材料，可来自反馈、漏斗或模型能力卡。", "证据必须可追溯。"),
            _step("flow", "设计介入流程", "流程 + 短文本", "画出流程，并分别说明 AI 做什么、用户做什么、首版暂不做什么。", "流程保持最小闭环。"),
            _step("validation", "定义最小验证", "结构化文本", "说明验证方式、成功信号和停止条件。", "必须包含停止条件。"),
            _step("event", "事件后决策", "保持或调整 + 说明", "收到研发周期由三周缩短到十天、且只允许一次模型调用的变化后重新决策。", "不能跳过资源变化。"),
        ],
        event=TrialTaskEvent(actor="研发负责人", message="研发周期从三周缩短到十天，首版只允许一次模型调用。", instruction="保持或调整介入点与验证方案，并说明依据。"),
        coach_prompts=["你现在解决的是用户问题，还是在寻找一个能放 AI 的位置？", "哪两条材料最能支持这个介入点？", "如果验证失败，你准备停止什么？"],
        rubric=_rubric("用户洞察", "能从混杂反馈中界定一个真实阻塞点，并解释为什么适合由 AI 介入。"),
    ),
    "F-02": TrialTaskDefinition(
        id="F-02",
        track="feature",
        title="AI 功能上线了，为什么用户用一次就走？",
        subtitle="从首用流失定位可验证的问题",
        role_type="AI 功能产品经理",
        work_stage="上线复盘",
        primary_skill="数据驱动",
        supporting_skills=["用户洞察", "方案与交互"],
        estimated_minutes="25–35 分钟",
        difficulty="基础",
        role="你负责一个已经上线的 AI 功能。",
        background="功能有首用流量，但复用率明显偏低；团队对原因有多种解释。",
        goal="定位最可能的流失环节，提出一个可验证的产品改动。",
        constraints=["只能提出一个主假设", "证据需同时包含数据和用户反馈", "不能把问题笼统归因为模型不好"],
        steps=[
            _step("layer", "定位问题层", "单选 + 说明", "在发现、首用、质量、价值理解和复用中定位主要问题层。", "只选一个主问题层。"),
            _step("evidence", "组合证据", "多选 + 说明", "至少引用两项指标和两条用户反馈。", "数据与反馈都必须使用。"),
            _step("hypothesis", "提出主假设", "假设 + 改动", "写出一个可证伪假设和一个对应的产品改动。", "假设与改动一一对应。"),
            _step("metrics", "设置判定标准", "结构化文本", "定义核心指标、护栏指标和停止条件。", "不能只看点击率。"),
            _step("event", "事件后决策", "保持或调整 + 说明", "得知高级用户复用率为 26%、新用户仅 3% 后重新判断。", "明确说明用户分层如何影响结论。"),
        ],
        event=TrialTaskEvent(actor="数据分析师", message="补充分层数据：高级用户复用率 26%，新用户复用率 3%。", instruction="保持或调整主假设与产品改动，并说明分层依据。"),
        coach_prompts=["你定位的是流失发生的位置，还是流失的原因？", "哪一组数据与反馈能够互相印证？", "什么结果会推翻你的主假设？"],
        rubric=_rubric("数据驱动", "能把漏斗、分层指标和反馈连接成可证伪的单一假设。"),
    ),
    "F-03": TrialTaskDefinition(
        id="F-03",
        track="feature",
        title="这个 AI 功能的首版到底做到哪一步？",
        subtitle="在需求、风险和交付周期之间划定 MVP",
        role_type="AI 功能产品经理",
        work_stage="MVP 定义",
        primary_skill="方案与交互",
        supporting_skills=["用户洞察", "跨团队落地"],
        estimated_minutes="30–40 分钟",
        difficulty="基础",
        role="你负责把一个 AI 功能从概念推进到首版。",
        background="业务、用户和研发提出了六项需求，但首版资源有限。",
        goal="确定首版范围、关键流程和验收条件。",
        constraints=["六项需求都要明确归类", "流程控制在四到六步", "必须包含确认与失败恢复"],
        steps=[
            _step("scope", "划定首版范围", "分类", "将六项需求分为 Must、Should 和 Not now。", "每项需求只能归入一类。"),
            _step("flow", "绘制关键流程", "流程", "给出四到六步的首版主流程。", "流程不能超过六步。"),
            _step("control", "设计确认与恢复", "结构化文本", "说明用户确认点和失败恢复方式。", "两项都必须存在。"),
            _step("acceptance", "定义验收", "列表", "给出两到三项验收标准和一个反馈信号。", "验收标准必须可观察。"),
            _step("event", "隐私事件调整", "重新分类 + 说明", "出现新的隐私约束后重新划分需求或调整流程。", "明确指出被影响的需求和步骤。"),
        ],
        event=TrialTaskEvent(actor="法务同事", message="新增隐私要求：敏感内容不得默认进入模型上下文，且必须允许用户撤回。", instruction="重新检查首版范围和流程，说明具体调整。"),
        coach_prompts=["如果首版只能证明一件事，你要证明什么？", "用户在哪一步保留最终控制权？", "哪项需求看起来重要，但不属于首版闭环？"],
        rubric=_rubric("方案与交互", "能形成边界清楚、可恢复、可验收的最小流程。"),
    ),
    "A-01": TrialTaskDefinition(
        id="A-01",
        track="agent",
        title="这个任务应该让 Agent 自动做到哪一步？",
        subtitle="划分自动执行、用户确认与禁止自动化的边界",
        role_type="Agent 产品经理",
        work_stage="流程设计",
        primary_skill="AI 产品化",
        supporting_skills=["方案与交互", "风险判断"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你负责一个需要多步完成工作的 Agent。",
        background="团队希望提升自动化程度，但任务中包含信息缺失、外部操作和不可逆决策。",
        goal="设计 Agent 工作流并明确自动化边界。",
        constraints=["工作流控制在六到八步", "最多允许两次澄清", "必须定义失败降级和完成条件"],
        steps=[
            _step("workflow", "拆解工作流", "流程", "给出六到八步工作流，并标注 Agent、用户和外部系统角色。", "总步骤不超过八步。"),
            _step("boundary", "划分自动化边界", "三分类", "将关键动作分为自动执行、需用户确认和不得自动执行。", "每个关键动作必须归类。"),
            _step("clarify", "设计澄清", "列表", "给出 Agent 必须询问的澄清问题。", "最多两次澄清。"),
            _step("failure", "定义失败处理", "结构化文本", "指出失败节点、降级方案和完成条件。", "不能只写重试。"),
            _step("event", "延迟事件调整", "保持或调整 + 说明", "外部系统同步延迟增加到二十分钟后重新设计。", "说明对自动化边界的影响。"),
        ],
        event=TrialTaskEvent(actor="技术负责人", message="外部系统同步延迟可能达到 20 分钟，且无法保证回调顺序。", instruction="调整工作流、确认点或降级策略，并说明依据。"),
        coach_prompts=["哪些动作失败后无法低成本撤回？", "Agent 缺少什么信息时必须停下来问人？", "你定义的完成，是流程结束还是结果可用？"],
        rubric=_rubric("AI 产品化", "能基于风险和可逆性划分 Agent 的自动化边界。"),
    ),
    "A-02": TrialTaskDefinition(
        id="A-02",
        track="agent",
        title="这个 Agent 为什么总是失败？",
        subtitle="从 Bad Case 归因到系统性 Top 2",
        role_type="Agent 产品经理",
        work_stage="问题诊断",
        primary_skill="AI 产品化",
        supporting_skills=["数据驱动", "模型评测"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你负责排查一个多步骤 Agent 的线上失败。",
        background="团队整理了八个 Bad Case 和一组运行指标，需要判断最值得优先解决的系统性问题。",
        goal="完成归因、选出系统性 Top 2，并给出可验证的改进动作。",
        constraints=["八个案例都要归因", "Top 2 必须唯一", "每个 Top 问题都要有可追溯证据与验证计划"],
        steps=[
            _step("attribution", "完成案例归因", "案例分类 + 置信度", "为八个 Bad Case 选择归因并标注置信度。", "八个案例必须全部完成。"),
            _step("priority", "选择系统性 Top 2", "双选", "选出两个最值得优先解决的系统性问题。", "只能选择两个且不得重复。"),
            _step("evidence", "引用证据", "案例 + 指标 + 说明", "使用案例和运行指标支持 Top 2 判断。", "两个问题都必须有证据。"),
            _step("validation", "制定验证计划", "结构化文本", "为 Top 2 分别填写验证动作和预期信号。", "动作必须能够产生可观察信号。"),
            _step("event", "约束下重新排序", "保持或调整 + 说明", "模型效果无明显退化且当前不能更换模型时重新排序。", "必须说明约束如何影响排序。"),
        ],
        event=TrialTaskEvent(actor="算法负责人", message="离线评测显示模型效果没有明显退化，而且本周期无法更换基础模型。", instruction="重新排列 Top 2，并说明保持或调整的依据。"),
        coach_prompts=["这是单个案例的表象，还是能解释多个案例的系统性原因？", "你引用的证据能区分相关性和因果假设吗？", "在不能换模型的前提下，哪个验证动作信息增益最高？"],
        rubric=_rubric("AI 产品化", "能把 Bad Case 聚类为系统性原因，并据证据确定修复优先级。"),
    ),
    "A-03": TrialTaskDefinition(
        id="A-03",
        track="agent",
        title="Prompt、RAG、Tool、子 Agent，还是先别做？",
        subtitle="为问题选择最低成本且可验证的技术策略",
        role_type="Agent 产品经理",
        work_stage="技术方案选择",
        primary_skill="AI 产品化",
        supporting_skills=["技术理解", "风险判断"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你需要为一个 Agent 问题选择技术策略。",
        background="团队提出 Prompt、RAG、规则、Planner、Tool、子 Agent 和换模型等多种方案。",
        goal="比较至少三种策略，选出主方案和必要组合，并设计低成本验证。",
        constraints=["至少比较三种候选策略", "必须明确不选什么", "需要说明组合复杂度与风险"],
        steps=[
            _step("candidates", "选择候选策略", "多选", "从 Prompt、RAG、规则、Planner、Tool、子 Agent、换模型或暂不开发中选择至少三项比较。", "至少三项。"),
            _step("matrix", "建立策略矩阵", "矩阵", "比较各策略解决的问题、成本、时延、风险和验证方式。", "所有候选使用同一比较维度。"),
            _step("decision", "形成选择", "主方案 + 组合 + 不选", "说明主方案、必要组合以及当前不选择的策略。", "不能把所有策略都列为主方案。"),
            _step("validation", "低成本验证", "结构化文本", "给出主要风险和一个低成本验证方案。", "验证必须先于大规模开发。"),
            _step("event", "性能约束调整", "保持或调整 + 说明", "加入 P95 小于四秒、成本增幅小于 20% 的约束后重新决策。", "同时满足时延和成本边界。"),
        ],
        event=TrialTaskEvent(actor="平台负责人", message="新增上线约束：P95 响应时延必须小于 4 秒，单次成本增幅不得超过 20%。", instruction="调整策略组合和验证优先级，并说明取舍。"),
        coach_prompts=["你选择的技术是在解决根因，还是覆盖症状？", "哪一种策略能用最低成本先排除最大不确定性？", "组合策略增加的复杂度由什么收益来支付？"],
        rubric=_rubric("AI 产品化", "能把产品问题映射到适当技术能力，并控制组合复杂度。"),
    ),
    "P-01": TrialTaskDefinition(
        id="P-01",
        track="platform",
        title="三个团队都要 AI 能力，我们应该为谁定制？",
        subtitle="区分平台共性、业务定制与暂不承诺",
        role_type="AI 平台产品经理",
        work_stage="需求治理",
        primary_skill="AI 产品化",
        supporting_skills=["商业意识", "跨团队落地"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你负责一个同时服务多个业务团队的 AI 平台。",
        background="三个团队提出相似但不完全一致的 AI 能力需求，平台资源只能支持有限范围。",
        goal="划定平台边界并选择首个验证客户。",
        constraints=["所有需求都要分类", "平台能力只能保留三到四项", "必须定义首个客户和验证指标"],
        steps=[
            _step("classify", "需求分类", "三分类", "将需求分为平台能力、业务定制和 Not now。", "每项需求必须归类。"),
            _step("capabilities", "选择平台能力", "排序", "选择最优先的三到四项平台能力，并说明服务对象。", "最多四项。"),
            _step("boundary", "定义边界模板", "结构化文本", "写出平台提供什么、业务负责什么、哪些配置可开放。", "职责边界必须具体。"),
            _step("pilot", "确定试点", "指标 + 客户", "定义一个平台指标并选择首个试点客户。", "指标需能验证复用价值。"),
            _step("event", "基础设施约束调整", "保持或调整 + 说明", "基础设施只支持两种推理配置后重新决策。", "平台承诺不得超过基础设施边界。"),
        ],
        event=TrialTaskEvent(actor="基础设施负责人", message="本季度只能稳定支持两种推理配置，无法为每个团队维护独立配置。", instruction="调整平台边界、配置方案或试点顺序。"),
        coach_prompts=["哪些需求只是表面相似，实际不应该平台化？", "第一位客户能否验证未来复用，而不只是验证定制交付？", "平台不负责什么，需要写得和负责什么一样清楚。"],
        rubric=_rubric("AI 产品化", "能识别跨团队共性并形成可复用、可交付的平台边界。"),
    ),
    "P-02": TrialTaskDefinition(
        id="P-02",
        track="platform",
        title="AI 平台下一季度到底先解决什么？",
        subtitle="用漏斗与客户价值确定平台优先级",
        role_type="AI 平台产品经理",
        work_stage="季度规划",
        primary_skill="数据驱动",
        supporting_skills=["商业意识", "AI 产品化"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你负责制定 AI 平台下一季度的产品优先级。",
        background="需求工单、使用漏斗和客户反馈指向多个问题，但季度只能推进两个项目。",
        goal="定位主要瓶颈并选择两个季度项目。",
        constraints=["只能选择两个项目", "必须同时引用工单和漏斗", "每个项目需有独立指标"],
        steps=[
            _step("bottleneck", "定位漏斗瓶颈", "单选 + 说明", "指出平台使用漏斗中的主要瓶颈。", "只保留一个主瓶颈。"),
            _step("projects", "选择 Top 2 项目", "双选 + 排序", "选择并排序两个季度项目。", "只能选择两个。"),
            _step("evidence", "引用证据", "工单 + 漏斗 + 说明", "同时使用需求工单和漏斗数据支持选择。", "两类证据都必须引用。"),
            _step("metrics", "设置项目指标", "结构化文本", "为两个项目分别定义成功指标。", "项目和指标一一对应。"),
            _step("event", "商业事件调整", "保持或调整 + 说明", "得知大型客户贡献 42% 收入且更看重稳定性与监控后重新排序。", "说明客户价值如何进入排序。"),
        ],
        event=TrialTaskEvent(actor="商业负责人", message="大型客户贡献 42% 的收入，他们当前最在意稳定性和监控能力。", instruction="保持或调整季度 Top 2，并说明数据与商业价值的共同依据。"),
        coach_prompts=["工单数量最多的问题，一定是漏斗损失最大的问题吗？", "两个项目是否在解决同一个瓶颈？", "收入权重改变优先级时，哪些护栏仍不能放弃？"],
        rubric=_rubric("数据驱动", "能综合漏斗、工单与客户价值确定有限资源下的优先级。"),
    ),
    "P-03": TrialTaskDefinition(
        id="P-03",
        track="platform",
        title="RAG、Tools、Memory 怎样做成‘平台能力’？",
        subtitle="把技术组件定义成可配置、可治理的产品接口",
        role_type="AI 平台产品经理",
        work_stage="能力产品化",
        primary_skill="方案与交互",
        supporting_skills=["AI 产品化", "跨团队落地"],
        estimated_minutes="35–45 分钟",
        difficulty="进阶",
        role="你负责将 AI 技术组件建设为多个团队可复用的平台能力。",
        background="RAG、Tools 和 Memory 都有人提出平台化诉求，但业务边界、配置和治理方式尚不清楚。",
        goal="选择一个组件，定义其平台边界和首个可验证接口。",
        constraints=["只能选择一个组件作为本轮重点", "接口必须包含默认值、权限和失败处理", "必须选择试点"],
        steps=[
            _step("component", "选择平台组件", "单选 + 说明", "从 RAG、Tools、Memory 中选择一个作为本轮平台化重点。", "只选一个。"),
            _step("boundary", "划分职责", "双栏", "说明平台负责的部分与业务负责的部分。", "不能把业务逻辑全部吸收到平台。"),
            _step("interface", "设计接口卡", "结构化卡片", "定义输入、配置、默认值、权限和失败处理。", "五项必须完整。"),
            _step("pilot", "定义验证", "指标 + 试点", "给出平台指标和首个试点团队。", "指标需体现复用或治理价值。"),
            _step("event", "合规事件调整", "保持或调整 + 说明", "加入长期记忆需支持纠错与删除的合规要求后重新设计。", "受影响的数据必须可追踪和撤回。"),
        ],
        event=TrialTaskEvent(actor="合规负责人", message="任何长期保存的用户信息都必须支持来源追踪、用户纠错和彻底删除。", instruction="重新检查组件选择、接口和责任边界。"),
        coach_prompts=["你定义的是一个技术组件，还是一个业务可以安全使用的产品能力？", "默认值在降低接入成本的同时引入了什么风险？", "试点成功后，第二个团队能复用多少？"],
        rubric=_rubric("方案与交互", "能把技术组件转化为边界、接口、默认值与治理机制清楚的平台产品。"),
    ),
    "M-01": TrialTaskDefinition(
        id="M-01",
        track="model",
        title="整体指标变好了，这个模型真的能上线吗？",
        subtitle="从平均分走向分层风险与上线决策",
        role_type="模型产品经理",
        work_stage="上线评审",
        primary_skill="模型评测",
        supporting_skills=["数据驱动", "风险判断"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你负责评审一个候选模型是否可以进入线上。",
        background="候选模型整体指标提升，但不同用户与场景下的表现并不一致。",
        goal="做出全量、灰度或不上线的决策，并设计下一步验证。",
        constraints=["核心指标最多三个", "必须排序", "必须说明风险、缺口和灰度方案"],
        steps=[
            _step("decision", "做出上线判断", "三选一 + 说明", "选择全量上线、灰度上线或不上线。", "只保留一个结论。"),
            _step("metrics", "选择核心指标", "排序", "选择并排序最多三个核心指标。", "最多三个。"),
            _step("risk", "识别风险与缺口", "列表", "说明当前证据中的风险和信息缺口。", "不能只复述平均指标。"),
            _step("gray", "设计灰度验证", "结构化文本", "给出灰度范围、监控信号和下一步验证。", "必须可停止或回滚。"),
            _step("event", "专业场景事件调整", "保持或调整 + 说明", "得知 32% 付费用户涉及专业术语场景后重新决策。", "必须考虑高价值用户的分层风险。"),
        ],
        event=TrialTaskEvent(actor="用户研究员", message="32% 的付费用户高频处理专业术语内容，而该场景当前样本覆盖有限。", instruction="保持或调整上线决策、灰度人群和指标。"),
        coach_prompts=["平均指标提升掩盖了哪些用户或场景？", "哪一个指标可以直接否决上线？", "灰度是在降低风险，还是只是延后发现风险？"],
        rubric=_rubric("模型评测", "能从分层表现、业务风险和证据缺口做出可回滚的上线判断。"),
    ),
    "M-02": TrialTaskDefinition(
        id="M-02",
        track="model",
        title="只有 100 条样本，你会怎么测试？",
        subtitle="在有限预算内设计高信息量评测集",
        role_type="模型产品经理",
        work_stage="评测设计",
        primary_skill="模型评测",
        supporting_skills=["数据驱动", "用户洞察"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你需要在只有 100 条人工评测预算的情况下验证模型。",
        background="目标场景包含常见请求、边界情况和少量高风险错误，团队需要一套可执行的测试方案。",
        goal="设计样本分配、评测维度和上线判定规则。",
        constraints=["样本总数必须等于 100", "失败类型控制在四到六类", "必须有一票否决项"],
        steps=[
            _step("taxonomy", "建立失败分类", "列表", "定义四到六类关键失败类型。", "总数在四到六类之间。"),
            _step("allocation", "分配样本", "数字分配", "把 100 条样本分配到各失败类型或场景。", "合计必须为 100。"),
            _step("dimensions", "定义评测维度", "列表", "说明每类样本观察的评测维度。", "维度必须可判定。"),
            _step("rules", "设置判定规则", "结构化文本", "定义通过线、一票否决项和评测人或评测方式。", "三项必须完整。"),
            _step("event", "严重错误事件调整", "保持或调整 + 说明", "平均分提升但严重语气错误从 2% 升至 8% 后重新决策。", "不能用平均分抵消一票否决风险。"),
        ],
        event=TrialTaskEvent(actor="评测负责人", message="新版本平均分上升，但严重语气错误率从 2% 上升到 8%。", instruction="调整样本分配、否决规则或上线建议。"),
        coach_prompts=["哪类错误虽然少见，但一旦发生就不能接受？", "100 条样本是在复刻真实分布，还是主动寻找风险？", "评测人之间不一致时如何处理？"],
        rubric=_rubric("模型评测", "能在有限样本中覆盖主要价值与严重风险，并形成可执行判定规则。"),
    ),
    "M-03": TrialTaskDefinition(
        id="M-03",
        track="model",
        title="Agent 到底应该记住用户什么？",
        subtitle="用价值、生命周期与合规边界设计记忆",
        role_type="模型产品经理",
        work_stage="记忆策略",
        primary_skill="数据驱动",
        supporting_skills=["AI 产品化", "风险判断"],
        estimated_minutes="30–40 分钟",
        difficulty="进阶",
        role="你负责设计 Agent 的用户记忆策略。",
        background="候选信息包含偏好、任务上下文、敏感信息和长期目标，但并非所有信息都值得或允许长期保存。",
        goal="划分记忆层级，选择最有价值的信息并定义生命周期与验证方式。",
        constraints=["所有候选数据都要归类", "长期记忆最多四项", "必须包含写入、更新、纠错和删除规则"],
        steps=[
            _step("buckets", "划分记忆层级", "三分类", "将候选数据分为不记忆、临时记忆和长期记忆。", "每项数据只能归入一类。"),
            _step("top", "选择长期 Top 4", "排序", "选择并排序最多四项长期记忆。", "最多四项。"),
            _step("lifecycle", "定义生命周期", "结构化文本", "说明写入、更新、纠错、过期和删除规则。", "生命周期必须闭环。"),
            _step("validation", "验证用户价值", "实验 + 指标", "设计价值验证并给出核心指标。", "不能只验证技术命中率。"),
            _step("event", "合规事件重分", "重新分类 + 说明", "新增合规约束后重新划分数据并调整 Top 4。", "明确受影响的数据和处理动作。"),
        ],
        event=TrialTaskEvent(actor="合规负责人", message="用户未明确知情的数据不得用于长期个性化，且必须提供查看、纠错和删除入口。", instruction="重新分类候选数据并调整长期记忆 Top 4。"),
        coach_prompts=["这条信息被记住后，用户能感受到什么具体价值？", "短期上下文为什么需要升级为长期记忆？", "用户改口或撤回时，系统如何真正忘记？"],
        rubric=_rubric("数据驱动", "能用可验证价值和生命周期规则决定记忆内容，而不是追求记得更多。"),
    ),
}


def get_task_definition(task_id: str) -> TrialTaskDefinition:
    try:
        return TASK_CATALOG[task_id]
    except KeyError as exc:
        raise KeyError(f"未知试路任务：{task_id}") from exc


def list_task_definitions() -> list[TrialTaskDefinition]:
    return list(TASK_CATALOG.values())


for _task_id, _task_definition in TASK_CATALOG.items():
    _rules = TASK_EVALUATION_RULES[_task_id]
    _task_definition.rubric = [
        TrialTaskRubricCriterion(
            dimension=dimension,
            weight=weight,
            observable_behavior=behavior,
        )
        for dimension, weight, behavior in _rules["rubric"]  # type: ignore[assignment]
    ]
    _task_definition.primary_skill = _task_definition.rubric[0].dimension
    _task_definition.supporting_skills = [
        item.dimension for item in _task_definition.rubric[1:3]
    ]
    _task_definition.level_anchors = _rules["anchors"]  # type: ignore[assignment]
    _task_definition.estimated_minutes = TASK_ESTIMATED_MINUTES[_task_id]
