"""Evaluate the multi-query RAG v2 path against pure local vector retrieval.

The default mode is cache-only and never calls Bailian.  ``--live`` is
required to create missing query vectors; document vectors are always read
from the local SQLite index and are never regenerated by this script.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.config import get_settings  # noqa: E402
from app.knowledge.hybrid import HybridKnowledgeRetriever  # noqa: E402
from app.knowledge.retriever import KnowledgeRetriever  # noqa: E402
from app.services.bailian_retrieval import DashScopeEmbeddingGateway  # noqa: E402
from app.services.model_response_cache import ModelResponseCache  # noqa: E402


ROLE_ANCHOR = "AI 产品经理 岗位职责 能力要求 工作内容"


class _NoRemoteEmbedding:
    def embed_many(self, *args: object, **kwargs: object) -> object:
        raise RuntimeError("RAG v2 离线评测只允许读取已有 Embedding 缓存")

    def embed(self, *args: object, **kwargs: object) -> object:
        raise RuntimeError("RAG v2 离线评测只允许读取已有 Embedding 缓存")


class _CountingEmbedding:
    def __init__(self, gateway: Any):
        self.gateway = gateway
        self.calls = 0
        self.items = 0

    def embed_many(self, texts: list[str], *, text_type: str) -> list[list[float]]:
        self.calls += 1
        self.items += len(texts)
        return self.gateway.embed_many(texts, text_type=text_type)


def _load_cases(path: Path) -> list[dict[str, str]]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise ValueError("RAG 评测集必须是数组。")
    cases: list[dict[str, str]] = []
    for item in raw:
        if not isinstance(item, dict) or not item.get("query") or not item.get("expected_heading"):
            raise ValueError("RAG 评测集存在缺少 query 或 expected_heading 的条目。")
        cases.append(
            {
                "query": str(item["query"]),
                "expected_heading": str(item["expected_heading"]),
            }
        )
    return cases


def _cache_key(retriever: KnowledgeRetriever, settings: Any, query: str) -> str:
    return ModelResponseCache.fingerprint(
        {
            "model": settings.bailian_embedding_model,
            "dimension": settings.bailian_embedding_dimension,
            "source_fingerprint": retriever.source_fingerprint,
            "query": query,
        }
    )


def _missing_queries(
    retriever: KnowledgeRetriever,
    settings: Any,
    cases: list[dict[str, str]],
) -> list[str]:
    cache = ModelResponseCache(settings.knowledge_db_path)
    queries = [ROLE_ANCHOR] + [case["query"] for case in cases]
    missing: list[str] = []
    for query in dict.fromkeys(queries):
        payload = cache.get("rag-query-embedding", _cache_key(retriever, settings, query))
        if payload is None:
            missing.append(query)
    return missing


def _prefill_missing_queries(
    retriever: KnowledgeRetriever,
    settings: Any,
    queries: list[str],
) -> tuple[int, int]:
    """Batch-create missing query vectors once and persist them locally."""

    if not queries:
        return 0, 0
    vectors = DashScopeEmbeddingGateway(settings).embed_many(queries, text_type="query")
    if len(vectors) != len(queries):
        raise ValueError("批量预热查询向量数量不正确。")
    cache = ModelResponseCache(settings.knowledge_db_path)
    for query, vector in zip(queries, vectors):
        cache.set(
            "rag-query-embedding",
            _cache_key(retriever, settings, query),
            {"embedding": vector},
        )
    batch_size = max(
        1,
        min(int(getattr(settings, "bailian_embedding_batch_size", 20)), 20),
    )
    return (len(queries) + batch_size - 1) // batch_size, len(queries)


def _rank(results: list[Any], expected: str) -> int | None:
    target = expected.lower()
    for index, chunk in enumerate(results, 1):
        if target in " > ".join(chunk.heading_path).lower():
            return index
    return None


def _metrics(ranks: list[int | None], limit: int) -> dict[str, Any]:
    total = max(1, len(ranks))
    return {
        "count": len(ranks),
        "hit_at_1": round(sum(rank == 1 for rank in ranks) / total, 6),
        f"hit_at_{limit}": round(
            sum(rank is not None and rank <= limit for rank in ranks) / total,
            6,
        ),
        f"mrr_at_{limit}": round(
            sum(1 / rank for rank in ranks if rank is not None and rank <= limit)
            / total,
            6,
        ),
    }


def _unique_heading_ratio(results: list[Any]) -> float:
    if not results:
        return 0.0
    return len({" > ".join(chunk.heading_path) for chunk in results}) / len(results)


def main() -> int:
    parser = argparse.ArgumentParser(description="评估 RAG v2 多查询 + RRF/MMR")
    parser.add_argument("--cases", type=Path, default=ROOT / "scripts/rag_eval_cases.json")
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--live", action="store_true", help="允许为缺失查询向量调用百炼")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "evaluation-results/rag-v2",
    )
    args = parser.parse_args()

    settings = replace(get_settings(), rag_retriever_mode="vector")
    cases = _load_cases(args.cases)
    base = KnowledgeRetriever(settings.knowledge_dir, settings.knowledge_db_path)
    missing = _missing_queries(base, settings, cases)
    if missing and not args.live:
        print(
            f"离线评测缺少 {len(missing)} 条查询向量；未调用百炼。"
            "需要时请显式增加 --live。",
            file=sys.stderr,
        )
        return 2
    prefill_calls = 0
    prefill_items = 0
    if missing:
        prefill_calls, prefill_items = _prefill_missing_queries(base, settings, missing)

    baseline = HybridKnowledgeRetriever(
        settings.knowledge_dir,
        settings.knowledge_db_path,
        settings=settings,
        embedding_gateway=(
            DashScopeEmbeddingGateway(settings) if args.live else _NoRemoteEmbedding()
        ),
    )
    counted_gateway = _CountingEmbedding(
        DashScopeEmbeddingGateway(settings) if args.live else _NoRemoteEmbedding()
    )
    v2 = HybridKnowledgeRetriever(
        settings.knowledge_dir,
        settings.knowledge_db_path,
        settings=settings,
        embedding_gateway=counted_gateway,
    )

    baseline_ranks: list[int | None] = []
    v2_ranks: list[int | None] = []
    baseline_diversity: list[float] = []
    v2_diversity: list[float] = []
    coverage: list[float] = []
    details: list[dict[str, Any]] = []
    for case in cases:
        baseline_results = baseline.search(
            case["query"],
            corpus="career",
            document_id="job-ai-product-manager-v1",
            limit=args.limit,
        )
        v2_results = v2.search_many(
            [ROLE_ANCHOR, case["query"]],
            corpus="career",
            document_id="job-ai-product-manager-v1",
            limit=args.limit,
        )
        baseline_rank = _rank(baseline_results, case["expected_heading"])
        v2_rank = _rank(v2_results, case["expected_heading"])
        baseline_ranks.append(baseline_rank)
        v2_ranks.append(v2_rank)
        baseline_diversity.append(_unique_heading_ratio(baseline_results))
        v2_diversity.append(_unique_heading_ratio(v2_results))
        coverage.append(float(v2.last_diagnostics.get("query_coverage", 0.0)))
        details.append(
            {
                "query": case["query"],
                "expected_heading": case["expected_heading"],
                "baseline_rank": baseline_rank,
                "v2_rank": v2_rank,
                "v2_mode": v2.last_diagnostics.get("mode"),
                "v2_query_coverage": v2.last_diagnostics.get("query_coverage"),
            }
        )

    baseline_metrics = _metrics(baseline_ranks, args.limit)
    v2_metrics = _metrics(v2_ranks, args.limit)
    report = {
        "report_version": "rag-eval-v2",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "dataset": str(args.cases),
        "query_count": len(cases),
        "k": args.limit,
        "role_anchor": ROLE_ANCHOR,
        "embedding_model": settings.bailian_embedding_model,
        "live": bool(args.live),
        "missing_vectors_before_run": missing,
        "new_embedding_api_calls": prefill_calls + counted_gateway.calls,
        "new_embedding_items": prefill_items + counted_gateway.items,
        "baseline_pure_vector": baseline_metrics,
        "v2_multi_query_rrf_mmr": v2_metrics,
        "delta": {
            key: round(v2_metrics[key] - baseline_metrics[key], 6)
            for key in ("hit_at_1", f"hit_at_{args.limit}", f"mrr_at_{args.limit}")
        },
        "avg_unique_heading_ratio": {
            "baseline": round(sum(baseline_diversity) / max(1, len(baseline_diversity)), 6),
            "v2": round(sum(v2_diversity) / max(1, len(v2_diversity)), 6),
        },
        "v2_query_coverage_avg": round(sum(coverage) / max(1, len(coverage)), 6),
        "details": details,
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (args.output_dir / "report.md").write_text(
        "# RAG v2 多查询评测\n\n"
        f"- 查询数：{len(cases)}\n"
        f"- 纯向量 Hit@1：{baseline_metrics['hit_at_1']:.1%}\n"
        f"- RAG v2 Hit@1：{v2_metrics['hit_at_1']:.1%}\n"
        f"- 纯向量 Hit@{args.limit}：{baseline_metrics[f'hit_at_{args.limit}']:.1%}\n"
        f"- RAG v2 Hit@{args.limit}：{v2_metrics[f'hit_at_{args.limit}']:.1%}\n"
        f"- 纯向量 MRR@{args.limit}：{baseline_metrics[f'mrr_at_{args.limit}']:.1%}\n"
        f"- RAG v2 MRR@{args.limit}：{v2_metrics[f'mrr_at_{args.limit}']:.1%}\n"
        f"- 新增 Embedding 调用：{counted_gateway.calls} 次，文本 {counted_gateway.items} 条\n"
        f"- 平均不同章节占比：纯向量 {report['avg_unique_heading_ratio']['baseline']:.1%}，"
        f"RAG v2 {report['avg_unique_heading_ratio']['v2']:.1%}\n",
        encoding="utf-8",
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
